<script setup lang="ts">
   definePageMeta({
      layout: "admin",
   });
</script>

<template>
   <div>Page: admin/index</div>
   <div>Page: admin/index</div>
   <div>Page: admin/index</div>
   <div>Page: admin/index</div>
   <div>Page: admin/index</div>
   <div>Page: admin/index</div>
   <div>Page: admin/index</div>
   <div>Page: admin/index</div>
   <div>Page: admin/index</div>
   <div>Page: admin/index</div>
   <div>Page: admin/index</div>
   <div>Page: admin/index</div>
   <div>Page: admin/index</div>
   <div>Page: admin/index</div>
   <div>Page: admin/index</div>
   <div>Page: admin/index</div>
   <div>Page: admin/index</div>
   <div>Page: admin/index</div>
   <div>Page: admin/index</div>
   <div>Page: admin/index</div>
   <div>Page: admin/index</div>
   <div>Page: admin/index</div>
   <div>Page: admin/index</div>
   <div>Page: admin/index</div>
   <div>Page: admin/index</div>
   <div>Page: admin/index</div>
   <div>Page: admin/index</div>
   <div>Page: admin/index</div>
   <div>Page: admin/index</div>
   <div>Page: admin/index</div>
   <div>Page: admin/index</div>
   <div>Page: admin/index</div>
   <div>Page: admin/index</div>
   <div>Page: admin/index</div>
   <div>Page: admin/index</div>
   <div>Page: admin/index</div>
   <div>Page: admin/index</div>
   <div>Page: admin/index</div>
   <div>Page: admin/index</div>
   <div>Page: admin/index</div>
   <div>Page: admin/index</div>
   <div>Page: admin/index</div>
   <div>Page: admin/index</div>
   <div>Page: admin/index</div>
   <div>Page: admin/index</div>
   <div>Page: admin/index</div>
   <div>Page: admin/index</div>
   <div>Page: admin/index</div>
   <div>Page: admin/index</div>
   <div>Page: admin/index</div>
   <div>Page: admin/index</div>
   <div>Page: admin/index</div>
   <div>Page: admin/index</div>
   <div>Page: admin/index</div>
   <div>Page: admin/index</div>
   <div>Page: admin/index</div>
   <div>Page: admin/index</div>
   <div>Page: admin/index</div>
   <div>Page: admin/index</div>
   <div>Page: admin/index</div>
   <div>Page: admin/index</div>
   <div>Page: admin/index</div>
   <div>Page: admin/index</div>
   <div>Page: admin/index</div>
   <div>Page: admin/index</div>
   <div>Page: admin/index</div>
   <div>Page: admin/index</div>
   <div>Page: admin/index</div>
   <div>Page: admin/index</div>
   <div>Page: admin/index</div>
   <div>Page: admin/index</div>
   <div>Page: admin/index</div>
   <div>Page: admin/index</div>
   <div>Page: admin/index</div>
   <div>Page: admin/index</div>
   <div>Page: admin/index</div>
   <div>Page: admin/index</div>
   <div>Page: admin/index</div>
   <div>Page: admin/index</div>
   <div>Page: admin/index</div>
   <div>Page: admin/index</div>
   <div>Page: admin/index</div>
   <div>Page: admin/index</div>
   <div>Page: admin/index</div>
</template>

<style scoped></style>
